name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testcov:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        name: JEST Tests                  # Name of the check run which will be created
        path: TestProject1/TestResults/*.trx                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx           # Format of test results
