name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testcov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet test --logger "trx;LogFileName=test-results.trx"

  test-report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        name: Tests
        path: TestProject1/TestResults/*.trx
        reporter: dotnet-trx           # Format of test results
