name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testcov:
    runs-on: ubuntu-latest
    steps:
        - name: use this action, test solution dir
          uses: zyborg/dotnet-tests-report@v1
          with:
            project_path: test/TestProject1.sln
            report_name: my_project_tests
            report_title: My Project Tests
            msbuild_verbosity: d
